[package]
name = "pyvsb-to-cloud"
version = "0.1.0"
authors = ["Dmitry Konishchev"]

[dependencies]
ansi_term = "*"
atty = "*"
bytes = "*"
bzip2 = "*"
chrono = "*"
clap = "*"
digest = "*"
fern = "*"
futures = "*"
hyper = "*"
hyper-tls = "*"
lazy_static = "*"
libc = "*"
log = "*"
md-5 = "*"
mime = "*"
nix = "*"
regex = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_urlencoded = "*"
serde_yaml = "*"
sha2 = "*"
shellexpand = "*"
tar = "*"
tokio-core = "*"