[package]
name = "pyvsb-to-cloud"
version = "0.1.0"
authors = ["Dmitry Konishchev"]

[dependencies]
bytes = "0.5.4"
bzip2 = "0.3.3"
chrono = "0.4.11"
clap = "2.33.1"
digest = "0.8.1"
easy-logging = "0.1.1"
lazy_static = "1.4.0"
libc = "0.2.71"
log = "0.4.8"
md-5 = "0.8.0"
mime = "0.3.16"
nix = "0.17.0"
regex = "1.3.9"
reqwest = { version = "0.10.6", features = ["blocking"] }
serde = "1.0.111"
serde_derive = "1.0.111"
serde_json = "1.0.53"
serde_urlencoded = "0.6.1"
serde_yaml = "0.8.12"
sha2 = "0.8.2"
shellexpand = "2.0.0"
tar = "0.4.28"
