[package]
name = "pyvsb-to-cloud"
version = "0.1.0"
authors = ["Dmitry Konishchev"]

[dependencies]
bytes = "*"
bzip2 = "*"
chrono = "*"
clap = "*"
digest = "*"
easy-logging = "*"
futures = "*"
hyper = "0.11.6"
hyper-tls = "0.1.2"
lazy_static = "*"
libc = "*"
log = "*"
md-5 = "*"
mime = "*"
nix = "*"
regex = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_urlencoded = "*"
serde_yaml = "*"
sha2 = "*"
shellexpand = "*"
tar = "*"
tokio-core = "*"
