[package]
name = "pyvsb-to-cloud"
version = "0.1.0"
edition = "2018"
authors = ["Dmitry Konishchev"]

[dependencies]
bytes = "0.5.6"
bzip2 = "0.4.1"
chrono = "0.4.15"
clap = "2.33.3"
digest = "0.9.0"
easy-logging = "0.1.1"
lazy_static = "1.4.0"
libc = "0.2.76"
log = "0.4.11"
md-5 = "0.9.1"
mime = "0.3.16"
nix = "0.18.0"
regex = "1.3.9"
reqwest = { version = "0.10.8", features = ["blocking"] }
serde = "1.0.115"
serde_derive = "1.0.115"
serde_json = "1.0.57"
serde_urlencoded = "0.6.1"
serde_yaml = "0.8.13"
sha2 = "0.9.1"
shellexpand = "2.0.0"
tar = "0.4.29"
