[package]
name = "pyvsb-to-cloud"
version = "0.1.0"
authors = ["Dmitry Konishchev"]

[dependencies]
ansi_term = "*"
atty = "*"
chrono = "*"
fern = "*"
futures = "*"
hyper = "*"
hyper-tls = "*"
log = "*"
mime = "*"
nix = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
tar = "*"
tokio-core = "*"